#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CORALNPU_ROOT="${CORALNPU_ROOT:-$(git -C "${SCRIPT_DIR}" rev-parse --show-toplevel)}"
TVM_VENV="${TVM_VENV:-/home/wangyy/001_research/virtualenv/tvm18-py3_10/bin/activate}"

MODEL_MODE="${MODEL_MODE:-quant}"
if [[ "${MODEL_MODE}" != "quant" && "${MODEL_MODE}" != "float" ]]; then
  echo "MODEL_MODE must be either 'quant' or 'float', got: ${MODEL_MODE}" >&2
  exit 1
fi

MODEL_PATH="${MODEL_PATH:-${SCRIPT_DIR}/onnx/${MODEL_MODE}/model.onnx}"
OUTPUT_DIR="${OUTPUT_DIR:-${SCRIPT_DIR}/generated/tvm_rv32_${MODEL_MODE}}"
LOG_DIR="${LOG_DIR:-${SCRIPT_DIR}/logs}"

if [[ -z "${CORALNPU_RV32_TOOLCHAIN_DIR:-}" ]]; then
  BAZEL_OUTPUT_BASE="$(cd "${CORALNPU_ROOT}" && bazel --batch info output_base)"
  CORALNPU_RV32_TOOLCHAIN_DIR="${BAZEL_OUTPUT_BASE}/external/toolchain_coralnpu_v2/bin"
fi

CROSS_COMPILER="${CROSS_COMPILER:-${CORALNPU_RV32_TOOLCHAIN_DIR}/riscv32-unknown-elf-gcc}"
CROSS_COMPILER_OPTIONS="${CROSS_COMPILER_OPTIONS:-"-O3 -v -march=rv32imf_zve32x_zicsr_zifencei_zbb -mabi=ilp32 -I. -Iartifacts"}"
if [[ "${MODEL_MODE}" == "quant" ]]; then
  DEFAULT_TVM_TARGET="c, rootbed-npu type=soft skip_normalize=true output_int=true"
else
  DEFAULT_TVM_TARGET="c, rootbed-npu type=soft skip_normalize=false output_int=false"
fi
TVM_TARGET="${TVM_TARGET:-${DEFAULT_TVM_TARGET}}"
TVM_TARGET_C_MCPU="${TVM_TARGET_C_MCPU:-rootbed}"

mkdir -p "${OUTPUT_DIR}" "${LOG_DIR}"

if [[ ! -f "${TVM_VENV}" ]]; then
  echo "TVM virtualenv activation script not found: ${TVM_VENV}" >&2
  exit 1
fi

if [[ ! -x "${CROSS_COMPILER}" ]]; then
  echo "Coral NPU RV32 cross compiler not found: ${CROSS_COMPILER}" >&2
  exit 1
fi

if [[ ! -f "${MODEL_PATH}" ]]; then
  echo "ONNX model not found: ${MODEL_PATH}" >&2
  exit 1
fi

source "${TVM_VENV}"

python "${SCRIPT_DIR}/compilation/tinyml_benchmark.py" \
  --model_path "${MODEL_PATH}" \
  --compilation_path "${OUTPUT_DIR}" \
  --cross_compiler "${CROSS_COMPILER}" \
  --cross_compiler_options "${CROSS_COMPILER_OPTIONS}" \
  --target "${TVM_TARGET}" \
  --target_c_mcpu "${TVM_TARGET_C_MCPU}" \
  --keep_libc_files \
  --log_file "${LOG_DIR}/tvm_compile.log"

cp "${OUTPUT_DIR}/artifacts/mod.a" "${SCRIPT_DIR}/mod.a"
cp "${OUTPUT_DIR}/artifacts/tvmgen_default.h" "${SCRIPT_DIR}/tvmgen_default.h"

INPUT_FIELD="$(awk '
  /struct tvmgen_default_inputs/ { in_inputs = 1; next }
  in_inputs && /};/ { exit }
  in_inputs && /void\*/ { gsub(";", "", $2); print $2; exit }
' "${SCRIPT_DIR}/tvmgen_default.h")"

BIAS_VALUE="$(sed -n 's/.*tvmgen_default_bias_data.*{\([^}]*\)}.*/\1/p' "${SCRIPT_DIR}/tvmgen_default.h" | cut -d',' -f1 | xargs || true)"
SCALE_VALUE="$(sed -n 's/.*tvmgen_default_scale_data.*{\([^}]*\)}.*/\1/p' "${SCRIPT_DIR}/tvmgen_default.h" | cut -d',' -f1 | xargs || true)"
SHIFT_VALUE="$(sed -n 's/.*tvmgen_default_shift_data.*{\([^}]*\)}.*/\1/p' "${SCRIPT_DIR}/tvmgen_default.h" | cut -d',' -f1 | xargs || true)"

if [[ -z "${INPUT_FIELD}" ]]; then
  echo "Could not derive TVM input field from ${SCRIPT_DIR}/tvmgen_default.h" >&2
  exit 1
fi

{
  echo "#ifndef TESTS_COCOTB_TUTORIAL_TI_ONNX_MODEL_QUANT_MODEL_ABI_H_"
  echo "#define TESTS_COCOTB_TUTORIAL_TI_ONNX_MODEL_QUANT_MODEL_ABI_H_"
  echo "#define TVMGEN_DEFAULT_INPUT_FIELD ${INPUT_FIELD}"
  echo "#endif"
} >"${SCRIPT_DIR}/model_abi.h"

{
  echo "# Generated by compile_onnx_tvm_for_coralnpu.sh"
  echo "INPUT_FIELD = \"${INPUT_FIELD}\""
  if [[ -n "${BIAS_VALUE}" && -n "${SCALE_VALUE}" && -n "${SHIFT_VALUE}" ]]; then
    echo "BIAS = ${BIAS_VALUE}"
    echo "SCALE = ${SCALE_VALUE}"
    echo "SHIFT = ${SHIFT_VALUE}"
  else
    echo "BIAS = None"
    echo "SCALE = None"
    echo "SHIFT = None"
  fi
} >"${SCRIPT_DIR}/model_abi.py"

echo "Updated ${SCRIPT_DIR}/mod.a and ${SCRIPT_DIR}/tvmgen_default.h for MODEL_MODE=${MODEL_MODE}"
