/*****************************************************************************/
/* Copyright (c) 2026                                                        */
/*****************************************************************************/
/*
 * Generated by Rootbed MCU NNC 1.0
 * cross-compiler: /home/wangyy/.cache/bazel/_bazel_wangyy/f5fc6ae1de374dadc178c2e803fe3ac1/external/toolchain_coralnpu_v2/bin/riscv32-unknown-elf-gcc
 * cross-compiler-opts: -O3 -v -march=rv32imf_zve32x_zicsr_zifencei_zbb -mabi=ilp32 -I. -Iartifacts
 * input model file: /home/wangyy/002_research/coralnpu/tests/cocotb/tutorial/ti_onnx_model_quant/onnx/quant/model.onnx
 * module name: default
 */

#ifndef TVMGEN_DEFAULT_H_
#define TVMGEN_DEFAULT_H_
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Symbol defined when running model on the host processor */
#define TVMGEN_DEFAULT_ROOTBED_NPU_SOFT
#ifdef TVMGEN_DEFAULT_ROOTBED_NPU
	#error Conflicting definition for where model should run.
#endif

/* The generated model library expects the following inputs/outputs:
 * Inputs:
 *    Tensor[(1, 1, 256, 1), int8]
 * Outputs:
 *    Tensor[(1, 2), int8]
 */

/* Input feature normalization parameters:
 *   input_int = clip(((int32_t)((input_float + bias) * scale)) >> shift, min, max)
 *   where (min, max) = (-128, 127) if int8 type, (0, 255) if uint8 type
 */
#define TVMGEN_DEFAULT_BIAS_LEN 1
#define TVMGEN_DEFAULT_SCALE_LEN 1
#define TVMGEN_DEFAULT_SHIFT_LEN 1
extern const float tvmgen_default_bias_data[] __attribute__((weak)) = {21.318298};
extern const int32_t tvmgen_default_scale_data[] __attribute__((weak)) = {186};
extern const int32_t tvmgen_default_shift_data[] __attribute__((weak)) = {7};


/*!
 * \brief Input tensor pointers for TVM module "default" 
 */
struct tvmgen_default_inputs {
  void* onnx__Add_0;
};

/*!
 * \brief Output tensor pointers for TVM module "default" 
 */
struct tvmgen_default_outputs {
  void* output;
};

/*!
 * \brief entrypoint function for TVM module "default"
 * \param inputs Input tensors for the module 
 * \param outputs Output tensors for the module 
 */
int32_t tvmgen_default_run(
  struct tvmgen_default_inputs* inputs,
  struct tvmgen_default_outputs* outputs
);
/*!
 * \brief Workspace size for TVM module "default" 
 */
#define TVMGEN_DEFAULT_WORKSPACE_SIZE 5408

#ifdef __cplusplus
}
#endif

#endif // TVMGEN_DEFAULT_H_
