load("@rules_python//python:defs.bzl", "py_binary")

package(default_visibility = ["//visibility:public"])

py_binary(
    name = "run_dc_flow",
    srcs = ["run_dc_flow.py"],
    main = "run_dc_flow.py",
    python_version = "PY3",
    srcs_version = "PY3",
)
