-DVLEN_128
-DUSE_GENERIC
-Ihdl_note/verilog
-Ihdl_note/verilog/rvv/inc
-Ihdl_note/verilog/rvv/common
-Ihdl_note/verilog/rvv/design

hdl_note/verilog/ClockGate.sv
hdl_note/verilog/RstSync.sv
hdl_note/verilog/Sram.v
hdl_note/verilog/Sram_1rw_256x256.v
hdl_note/verilog/Sram_1rwm_256x288.v

hdl_note/verilog/rvv/common/adder.sv
hdl_note/verilog/rvv/common/arb_round_robin.sv
hdl_note/verilog/rvv/common/barrel_shifter.sv
hdl_note/verilog/rvv/common/cdffr.sv
hdl_note/verilog/rvv/common/compressor_3_2.sv
hdl_note/verilog/rvv/common/compressor_4_2.sv
hdl_note/verilog/rvv/common/dff.sv
hdl_note/verilog/rvv/common/edff.sv
hdl_note/verilog/rvv/common/edff_2d.sv
hdl_note/verilog/rvv/common/fifo_flopped.sv
hdl_note/verilog/rvv/common/fifo_flopped_2w2r.sv
hdl_note/verilog/rvv/common/fifo_flopped_4w2r.sv
hdl_note/verilog/rvv/common/handshake_ff.sv
hdl_note/verilog/rvv/common/handshake_multi_fifo.sv
hdl_note/verilog/rvv/common/multi_fifo.sv
hdl_note/verilog/rvv/common/openFifo4_flopped_ptr.sv
hdl_note/verilog/rvv/common/openFifo8_flopped_2w2r.sv

hdl_note/verilog/rvv/design/Aligner.sv
hdl_note/verilog/rvv/design/MultiFifo.sv
hdl_note/verilog/rvv/design/RvvCore.sv
hdl_note/verilog/rvv/design/RvvFrontEnd.sv
hdl_note/verilog/rvv/design/rvv_backend.sv
hdl_note/verilog/rvv/design/rvv_backend_arb.sv
hdl_note/verilog/rvv/design/rvv_backend_alu.sv
hdl_note/verilog/rvv/design/rvv_backend_alu_unit.sv
hdl_note/verilog/rvv/design/rvv_backend_alu_unit_addsub.sv
hdl_note/verilog/rvv/design/rvv_backend_alu_unit_execution_p1.sv
hdl_note/verilog/rvv/design/rvv_backend_alu_unit_mask.sv
hdl_note/verilog/rvv/design/rvv_backend_alu_unit_mask_viota.sv
hdl_note/verilog/rvv/design/rvv_backend_alu_unit_other.sv
hdl_note/verilog/rvv/design/rvv_backend_alu_unit_shift.sv
hdl_note/verilog/rvv/design/rvv_backend_decode.sv
hdl_note/verilog/rvv/design/rvv_backend_decode_ctrl.sv
hdl_note/verilog/rvv/design/rvv_backend_decode_de2.sv
hdl_note/verilog/rvv/design/rvv_backend_decode_unit.sv
hdl_note/verilog/rvv/design/rvv_backend_decode_unit_ari.sv
hdl_note/verilog/rvv/design/rvv_backend_decode_unit_ari_de2.sv
hdl_note/verilog/rvv/design/rvv_backend_decode_unit_de2.sv
hdl_note/verilog/rvv/design/rvv_backend_decode_unit_lsu.sv
hdl_note/verilog/rvv/design/rvv_backend_decode_unit_lsu_de2.sv
hdl_note/verilog/rvv/design/rvv_backend_dispatch.sv
hdl_note/verilog/rvv/design/rvv_backend_dispatch_bypass.sv
hdl_note/verilog/rvv/design/rvv_backend_dispatch_ctrl.sv
hdl_note/verilog/rvv/design/rvv_backend_dispatch_operand.sv
hdl_note/verilog/rvv/design/rvv_backend_dispatch_opr_byte_type.sv
hdl_note/verilog/rvv/design/rvv_backend_dispatch_raw_uop_rob.sv
hdl_note/verilog/rvv/design/rvv_backend_dispatch_raw_uop_uop.sv
hdl_note/verilog/rvv/design/rvv_backend_dispatch_structure_hazard.sv
hdl_note/verilog/rvv/design/rvv_backend_div.sv
hdl_note/verilog/rvv/design/rvv_backend_div_unit.sv
hdl_note/verilog/rvv/design/rvv_backend_div_unit_divider.sv
hdl_note/verilog/rvv/design/rvv_backend_fdiv_wrapper.sv
hdl_note/verilog/rvv/design/rvv_backend_fma.sv
hdl_note/verilog/rvv/design/rvv_backend_fma_wrapper.sv
hdl_note/verilog/rvv/design/rvv_backend_freduction.sv
hdl_note/verilog/rvv/design/rvv_backend_lsu_remap.sv
hdl_note/verilog/rvv/design/rvv_backend_mac_unit.sv
hdl_note/verilog/rvv/design/rvv_backend_mul_unit.sv
hdl_note/verilog/rvv/design/rvv_backend_mul_unit_mul8.sv
hdl_note/verilog/rvv/design/rvv_backend_mulmac.sv
hdl_note/verilog/rvv/design/rvv_backend_pmtrdt.sv
hdl_note/verilog/rvv/design/rvv_backend_pmtrdt_unit.sv
hdl_note/verilog/rvv/design/rvv_backend_pmtrdt_unit_permutation.sv
hdl_note/verilog/rvv/design/rvv_backend_pmtrdt_unit_reduction.sv
hdl_note/verilog/rvv/design/rvv_backend_pmtrdt_unit_reduction_alu.sv
hdl_note/verilog/rvv/design/rvv_backend_retire.sv
hdl_note/verilog/rvv/design/rvv_backend_retire_waw.sv
hdl_note/verilog/rvv/design/rvv_backend_rob.sv
hdl_note/verilog/rvv/design/rvv_backend_sqrt7_rec7.sv
hdl_note/verilog/rvv/design/rvv_backend_vrf.sv
hdl_note/verilog/rvv/design/rvv_backend_vrf_reg.sv
